### ISSUE TITLE
Move all item for Trash the All Item not show item 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/crm-app#29]
1 Check All item is Trash 
2 Message show successful 
3 But All item not show anything 
![image](https://user-images.githubusercontent.com/44457418/221528694-bba42563-0e97-4758-a1b5-568b7c1bc0f3.png)

**Comment by nhatvippro** [comment]
@VanTrieuThanh i was checked, its work, pls check again a @vietredweb, tell me if it doesn't work

**Comment by huynhngocgiau** [comment]
I'm check, it's work c @VanTrieuThanh 
![image](https://user-images.githubusercontent.com/79819354/221805070-a8a4f8d4-a132-474c-8ad2-4660a70e9a19.png)
