### ISSUE TITLE
Login - Remove Authentication Login

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/crm-app#34]

**Comment by huynhngocgiau** [comment]
Background: #EDEFF0
The login page has a background
![image](https://user-images.githubusercontent.com/79819354/224282921-263c9d51-b1bc-4f04-9542-400eb64f231d.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/224288634-7b804e7f-c32b-4976-8abf-3958928ee671.png)
